CREATE TABLE IF NOT EXISTS cards (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100),
  suit VARCHAR(50),
  point_value INTEGER,
  strength INTEGER,
  front_image_path VARCHAR(255)
);

INSERT INTO cards (name, suit, point_value, strength, front_image_path) VALUES
('ten', 'club', 1, -5, '01-club-ten.png'),
('jack', 'club', 2, -4, '02-club-jack.png'),
('rider', 'club', 3, -3, '03-club-rider.png'),
('queen', 'club', 4, -2, '04-club-queen.png'),
('king', 'club', 5, -1, '05-club-king.png'),
('ace', 'diamond', 1, -5, '06-diamond-ace.png'),
('jack', 'diamond', 2, -4, '07-diamond-jack.png'),
('rider', 'diamond', 3, -3, '08-diamond-rider.png'),
('queen', 'diamond', 4, -2, '09-diamond-queen.png'),
('king', 'diamond', 5, -1, '10-diamond-king.png'),
('ten', 'spade', 1, -5, '11-spade-ten.png'),
('jack', 'spade', 2, -4, '12-spade-jack.png'),
('rider', 'spade', 3, -3, '13-spade-rider.png'),
('queen', 'spade', 4, -2, '14-spade-queen.png'),
('king', 'spade', 5, -1, '15-spade-king.png'),
('ace', 'heart', 1, -5, '16-heart-ace.png'),
('jack', 'heart', 2, -4, '17-heart-jack.png'),
('rider', 'heart', 3, -3, '18-heart-rider.png'),
('queen', 'heart', 4, -2, '19-heart-queen.png'),
('king', 'heart', 5, -1, '20-heart-king.png'),
('tarokk', 'tarokk', 5, 1, '21-tarokk-one.png'),
('tarokk', 'tarokk', 1, 2, '22-tarokk-two.png'),
('tarokk', 'tarokk', 1, 3, '23-tarokk-three.png'),
('tarokk', 'tarokk', 1, 4, '24-tarokk-four.png'),
('tarokk', 'tarokk', 1, 5, '25-tarokk-five.png'),
('tarokk', 'tarokk', 1, 6, '26-tarokk-six.png'),
('tarokk', 'tarokk', 1, 7, '27-tarokk-seven.png'),
('tarokk', 'tarokk', 1, 8, '28-tarokk-eight.png'),
('tarokk', 'tarokk', 1, 9, '29-tarokk-nine.png'),
('tarokk', 'tarokk', 1, 10, '30-tarokk-ten.png'),
('tarokk', 'tarokk', 1, 11, '31-tarokk-eleven.png'),
('tarokk', 'tarokk', 1, 12, '32-tarokk-twelve.png'),
('tarokk', 'tarokk', 1, 13, '33-tarokk-thirteen.png'),
('tarokk', 'tarokk', 1, 14, '34-tarokk-fourteen.png'),
('tarokk', 'tarokk', 1, 15, '35-tarokk-fifteen.png'),
('tarokk', 'tarokk', 1, 16, '36-tarokk-sixteen.png'),
('tarokk', 'tarokk', 1, 17, '37-tarokk-seventeen.png'),
('tarokk', 'tarokk', 1, 18, '38-tarokk-eighteen.png'), 
('tarokk', 'tarokk', 1, 19, '39-tarokk-nineteen.png'),
('tarokk', 'tarokk', 1, 20, '40-tarokk-twenty.png'),
('tarokk', 'tarokk', 5, 21, '41-tarokk-twenty-one.png'),
('tarokk', 'tarokk', 5, 22, '42-tarokk-twenty-two.png');

